version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"

  cabinetry.jacobsanford.com:
    build:
      context: .
      args:
        - COMPOSER_DEPLOY_DEV=dev
    restart: always
    container_name: cabinetry.jacobsanford.com
    expose:
      - "80"
    ports:
      - "7080:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests:/app/tests
